### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by christopherjbaker** [renodevelopers/meetups#22]
There was a recent conversation between Simon Bauman and I on Facebook regarding Authentication. It occurred to me that this might be a good idea for a talk, which I would be willing to do.

But I need to know a) would you be interested in hearing a talk on this, and b) authentication is huge, what would you want to hear about?

Possible ideas:
- Authentication vs Authorization vs Encription
- Factors of Authentication. What does 2-factor authentication mean, why is it better, how can I do it myself? This naturally leads into time based security tokens.
- How secure is secure, how secure is "good enough", and where will it probably break down?

**Comment by w1zeman1p** [comment]
@HMUDesign  did this talk go down?

**Comment by w1zeman1p** [comment]
This is good stuff to talk about even if it did happen in 2014, lets revisit in July.

**Comment by w1zeman1p** [comment]
Any volunteers up for talking about Authentication?
