### ISSUE TITLE
Intro to Go

### ISSUE THREAD

**Issue by colinloretz** [renodevelopers/meetups#3]

**Comment by halfnibble** [comment]
I'm interesting in hearing more about Go.

**Comment by w1zeman1p** [comment]
This would be awesome! Pradeep from ClearPlan.io is going to give a talk on this. I'll nail down the dates.

**Comment by elskwid** [comment]
Excellent!!

**Comment by w1zeman1p** [comment]
Solid introduction to Go from @spot  https://github.com/spotlmnop/goLangIntro

Here's a followup using what we learned https://izen.me/2016/04/30/golearn/

Thanks again to clearplan.io and Pradeep for taking care of this one!
