### ISSUE TITLE
Ember.js Talk

### ISSUE THREAD

**Issue by ErikCH** [renodevelopers/meetups#38]
I've been learning Ember.js for the last few months. I wouldn't mind making a short presentation for it.

**Comment by elskwid** [comment]
@ErikCH We discussed doing this for 30-60 minutes. Do you have a time and how about planning for this being the main talk in February? If you're okay with that then please give me a title for the talk and a little bio.

**Comment by ErikCH** [comment]
If we could push this talk out even further that would be better. Unfortunately I have class every Monday until the beginning of May so I won't be able to make any of the meetings until then.

I'm trying to finish up my degree and the only day this class is offered is on Mondays at exactly the time this meeting is at. Sorry about that, I couldn't get around it this semester.

**Comment by ErikCH** [comment]
My Spring and Summer school classes are done so I'll have time again to do this talk, at least until August.

Let me know if you guys are still interested.

**Comment by w1zeman1p** [comment]
Did this ever happen? If not is it cool to move to Reno.js?

**Comment by elskwid** [comment]
@w1zeman1p if you want move it, move it! Additionally, tell me when would be good for the talk and I can give it as well.

**Comment by w1zeman1p** [comment]
How about April 12?

**Comment by ErikCH** [comment]
I'm OK with making this talk in Reno.js. Once again I'm off for the summer so I can probably jump in and do a talk sometime this summer.

**Comment by ErikCH** [comment]
@w1zeman1p Have you guys had an Ember talk yet?

**Comment by w1zeman1p** [comment]
We have not. It would be awesome if you could jump in on that one for us!

We have an opening Tue Jul 12 6:00 PM. Let me know if that works for you, @ErikCH

**Comment by ErikCH** [comment]
I can do that @w1zeman1p  July 12 :)
