### ISSUE TITLE
Reno Tracks Beta Ready

### ISSUE THREAD

**Issue by scaryuncledevin** [renodevelopers/meetups#47]
Wanted to make a quick shoutout that the beta for Reno Tracks is now available. Below is the link for the Google+ Community for users to join so they can opt into the beta and then get the app: https://plus.google.com/communities/107894878271175633612

**Comment by elskwid** [comment]
@scaryuncledevin would be great to get an update about Reno Tracks at one of our next meetings. Thanks!
