### ISSUE TITLE
ECMAScript 6

### ISSUE THREAD

**Issue by HMUDesign** [renodevelopers/meetups#52]
likely demoed (when possible) with iojs

**Comment by HMUDesign** [comment]
@elskwid I'm still available to do this. A request for this came up in conversation.

**Comment by elskwid** [comment]
@hmudesign - Wanna do this tomorrow? How long will you need?

**Comment by HMUDesign** [comment]
I can do this tomorrow, yes. ES6 is huge, so I'm preparing a list of all the things and was gonna let it be audience led with the particular topics. In that, it can be as long or as short as you need. 30-45 minutes would probably be good, but I could shorten it to 10 minutes or talk to 3 hours if you needed =P

**Comment by elskwid** [comment]
@HMUDesign you're on for tomorrow. 45 - 1hour is your block. Enjoy!!!
