### ISSUE TITLE
Controlling robots with Javascript, Ruby or Go

### ISSUE THREAD

**Issue by colinloretz** [renodevelopers/meetups#54]
An overview of Cylon, Artoo and Gobot to control robots (or hardware in general)!

**Comment by elskwid** [comment]
@colinloretz - I've asked @hmudesign how much time he needs for the ES6 talk. I'll get back to you soon.

**Comment by elskwid** [comment]
@colinloretz May is all you! ROBOTZ

**Comment by elskwid** [comment]
@colinloretz - can we put you on the schedule for July?

**Comment by colinloretz** [comment]
Yea lets do it in July.

**Comment by elskwid** [comment]
http://www.meetup.com/dev-reno/events/223313810/
