### ISSUE TITLE
devreno.org

### ISSUE THREAD

**Issue by underparnv** [renodevelopers/meetups#55]
Should I renew it, or let it go?

**Comment by elskwid** [comment]
@underparnv we've really been using meetup.com, I wonder if we should just point our domain there? What do you think?

**Comment by colinloretz** [comment]
@underparnv did you renew this? We have another use for it in mind too. If we could create a slack.devreno.org subdomain :D

**Comment by underparnv** [comment]
I have. Shoot me an email (dmosher@noip.com) with the target and I can set it up... Let me know what we want to point the root at also.

**Comment by elskwid** [comment]
@underparnv you can point root here: http://www.meetup.com/dev-reno/

**Comment by underparnv** [comment]
Done...will be live when the zone refreshes (about 5 minutes from now).

@colinloretz What is the target for slack.devreno.org?

**Comment by colinloretz** [comment]
@underparnv https://devreno.herokuapp.com/

**Comment by underparnv** [comment]
Please wait about 5 minutes or so for propagation and you should be all set!

**Comment by underparnv** [comment]
Confirmed live. :+1:

**Comment by colinloretz** [comment]
Woop! Thanks @underparnv
