### ISSUE TITLE
Short Intro to Django

### ISSUE THREAD

**Issue by halfnibble** [renodevelopers/meetups#56]
I don't know if anyone would be interested, but I could prepare a short Django tutorial with little advance notice.

**Comment by elskwid** [comment]
@halfnibble I would like this, we have a couple of talks in the works, what about something a little longer form and you do the June meeting?

**Comment by halfnibble** [comment]
Sure thing. When is the June meeting? I am going on vacation to LEGOland sometime in June.

**Comment by halfnibble** [comment]
BTW, I return from vacation on June 20th. So I can do the talk if there are people interested.

The title would be, "Rapid Web App Development w/ Python and Django."

**Comment by gwmccull** [comment]
I think that sounds interesting.  It's outside our normal scope of JS talks but I don't think that should prevent us from talking about it.  I'm a little more interested in the Python portion than the Django but both would probably be good to learn about.
What do other people think? 


     On Wednesday, May 20, 2015 1:24 AM, Josh <notifications@github.com> wrote:
   

 BTW, I return from vacation on June 20th. So I can do the talk if there are people interested.The title would be, "Rapid Web App Development w/ Python and Django."—

**Comment by halfnibble** [comment]
I'm also open in July if we are moving things back a month.

I thought about going over using Django's django-rest-framework in conjunction with a JS library like Backbone.js to make Single Page Apps, but I doubt I'd have enough time to get that far in one session.

**Comment by elskwid** [comment]
@halfnibble - we've had a schedule change - can you still take the talk this month?

**Comment by halfnibble** [comment]
I can do it this month, or next month--whichever works best. Just let me know the month so I make time to prepare an awesome, concise presentation. :)                                                                                                                                                                                                                                                                                                                                         Sent from my AMAZING BlackBerry Passport                                                                                                                                                                                                                From: Don MorrisonSent: Tuesday, June 16, 2015 8:49 AMTo: renodevelopers/meetupsReply To: renodevelopers/meetupsCc: JoshSubject: Re: [meetups] Short Intro to Django (#56)@halfnibble - we've had a schedule change - can you still take the talk this month?

—Reply to this email directly or view it on GitHub.

**Comment by elskwid** [comment]
Alright @halfnibble - you're on for next Monday! Confirm and I'll draw up the meeting and other stuff. (Give me a brief description of what you're talking about.)

**Comment by halfnibble** [comment]
"Rapid Web App Programming with Python and Django"Description: An uber brief introduction to the Python programming language, followed by a tutorial on creating database-driven web apps with Django‎.                                                                                                                                                                                                                                                                                                                                        Sent from my AMAZING BlackBerry Passport                                                                                                                                                                                                                From: Don MorrisonSent: Tuesday, June 16, 2015 11:07 AMTo: renodevelopers/meetupsReply To: renodevelopers/meetupsCc: JoshSubject: Re: [meetups] Short Intro to Django (#56)Alright @halfnibble - you're on for next Monday! Confirm and I'll draw up the meeting and other stuff. (Give me a brief description of what you're talking about.)

—Reply to this email directly or view it on GitHub.

**Comment by elskwid** [comment]
:+1:

**Comment by elskwid** [comment]
http://www.meetup.com/dev-reno/events/223313728/

**Comment by halfnibble** [comment]
Here is the slideshow for the presentation:
http://slides.com/halfnibble/django-intro

And here is the GitHub repo,
https://github.com/halfnibble/django-intro
