### ISSUE TITLE
TypeScript Presentation

### ISSUE THREAD

**Issue by staxmanade** [renodevelopers/meetups#58]
Hey @elskwid,

At the last meet-up you requested some talk proposals...

I'd be open to giving a talk on `TypeScript`. Let me know if that would suite the group.

Anyone: feel free to ask any specific questions you'd like addressed in the talk in this issue and I'll try to address any questions.

**Comment by elskwid** [comment]
Yay! Thanks for jumping in @staxmanade. You're on the schedule for September!

**Comment by elskwid** [comment]
Give me a title and a brief description when you can and I'll add it to the wiki and meetup.com

**Comment by elskwid** [comment]
@staxmanade I'd like to post the rough details for your talk. Care to give me a title and short description?

**Comment by staxmanade** [comment]
Bahh - I typed it in, but apparently didn't commit the message...

> Pro Tip: Rebooting your computer will erase anything you've typed into a `textarea` that has not been submitted to GitHub. :disappointed:

### Title:
```
Introduction to TypeScript.
```

### Description:
```
TypeScript is a language for application-scale JavaScript development. During the talk we'll introduce TypeScript, where it will help you, where you might struggle with it, and give you some tools to begin your own journey into this new language.

If we have time, we'll go through porting an existing JavaScript application to TypeScript and provide guidance and tips that could help you in your own projects.
```

**Comment by staxmanade** [comment]
@elskwid what day is this month's meeting? is it the 21st?

**Comment by elskwid** [comment]
@staxmanade it will be on the 28th. I'll post the meeting details tomorrow if that's okay with you?

**Comment by staxmanade** [comment]
:+1:

**Comment by elskwid** [comment]
Announced: http://www.meetup.com/dev-reno/events/225267537/ :trophy:

**Comment by HMUDesign** [comment]
omg 18 days in advance?

**Comment by elskwid** [comment]
I know, right?!?!
