### ISSUE TITLE
Intro to Smartwatch Programming

### ISSUE THREAD

**Issue by elskwid** [renodevelopers/meetups#59]
Joe Chavez has suggested a talk on smartwatch programming. More details ...

**Comment by gitizenme** [comment]
## Overview
In the presentation I'll do a brief review of the Smartwatch ecosystem and dive into the details of writing apps for the 3 main platforms: iOS, Pebble & Android Wear. This will be a 90% code focused session with a bit of opinion and prognostication. 

## Agenda
* What is a smartwatch?
* The market and opportunity
* Platforms
* Apple WatchOS
  * Architecture
  * SDK
  * Building an app
* Pebble
  * Architecture
  * SDK
  * Building an app
* Android Wear
  * Architecture
  * SDK
  * Building an app
* Conclusion
* Q&A

**Comment by elskwid** [comment]
Meetup [scheduled](http://www.meetup.com/dev-reno/events/225438498/) - will announce after the next meeting.

**Comment by elskwid** [comment]
Moving to November! http://www.meetup.com/dev-reno/events/225438498/

**Comment by w1zeman1p** [comment]
Awesome job, @gitizenme! :) Great talk about the differences between the platforms and tools available.
