### ISSUE TITLE
Talk on Ionic Mobile apps

### ISSUE THREAD

**Issue by staxmanade** [renodevelopers/meetups#61]
Hey @elskwid,

My Shawn @ucswift  has some good experience at building [Ionic](http://ionicframework.com/) apps and I think could put together a pretty good talk.

Sign him :up:

We use Ionic Framework for [Resgrid](http://resgrid.com/)

**Comment by w1zeman1p** [comment]
@ucswift. you down to talk about ionic framework at Reno.js in March?

**Comment by ucswift** [comment]
Yea sure thing, just lemme know!

**Comment by w1zeman1p** [comment]
Sweet! its March 8, 2016 @renocollective 6-8pm :) I'll put you down. Can you shoot me a quick bio for the site? (cjavilla@gmail.com)

**Comment by ucswift** [comment]
Awesome, will shoot you an email here shortly.

**Comment by w1zeman1p** [comment]
Thanks @ucswift awesome talk and great feedback :)
