### ISSUE TITLE
Django Rest Framework and Backbone.js

### ISSUE THREAD

**Issue by halfnibble** [renodevelopers/meetups#63]
I've been having tons of fun using the Django Rest Framework for Django in conjunction with Backbone.js for a client project, and would love to share what I've learned.

This presentation would spend about 30 minutes setting up a single model Django application and creating a RESTful API using the Django Rest Framework. Then another 30 minutes creating a web page and designing a simple Backbone.js Modell, View, and Router to interact with the API.

**Comment by w1zeman1p** [comment]
@halfnibble you still down to talk about this?

**Comment by halfnibble** [comment]
@w1zeman1p Sorry about the delay. I've been out of town. I am still interested in giving a talk on this. 

Note: I will be relocating to Seattle in July, so if I give a presentation, it would have to be before then.
