### ISSUE TITLE
Dynamic PDF generation with Charts (No CSS)

### ISSUE THREAD

**Issue by BlakeCampbells** [renodevelopers/meetups#64]
Hey I've been working on dynamic pdfs for a little while.
I found a way to do it without CSS, Phantom and saving to the disk at all. 

I'd love to present this.
I'm using Ruby on Rails, Prawn, Combine-PDF, and Gruff. 

I'll upload an example sometime this week. I was hoping to present at the November Meetup.

**Comment by elskwid** [comment]
Hi @BlakeCampbells - that sounds like fun! We've had some scheduling changes and have moved the October meetup to Nov 16th. If we're going to do a December meeting it will like be the 14th. Interested?

**Comment by BlakeCampbells** [comment]
I'm interested. That gives me plenty of prep time. 

Thank you!

**Comment by BlakeCampbells** [comment]
Yes I'm still doing this, I just saw this now

**Comment by BlakeCampbells** [comment]
https://github.com/BlakeCampbells/dynamic_pdfs

I have a repo I'm updating to show examples and usage.

**Comment by elskwid** [comment]
Scheduled! http://www.meetup.com/dev-reno/events/227339572/
