### ISSUE TITLE
ClojureScript/React overview

### ISSUE THREAD

**Issue by Seberius** [renodevelopers/meetups#67]
I would be willing to do a presentation on front end ClojureScript frameworks and their usage of React as the "view".  It would cover the Om.Next graph-query-view and re-frame/reagent "data driven loop" implementations, along with a basic overview of React and its place in vanilla javascript.

**Comment by w1zeman1p** [comment]
:+1:

**Comment by w1zeman1p** [comment]
Awesome idea, is it okay to move this to Reno.js? Seems focused enough on js to make sense.

**Comment by Seberius** [comment]
Sure, though I have never been to the meeting.  I thought I would change the focus from ClojureScript (CLJS) to React after talking to a few people about Om at the last meeting and the general interest in React itself.  The talk would cover:
- An intro to [React](https://github.com/facebook/react/), its role as the view and why it won (maybe) the front-end wars.
- React + [Flux](https://facebook.github.io/react/docs/flux-overview.html), a state management pattern in JS, covers manipulating DOM changes, etc. There was some interest in this in particular. (example code)
- [Reagent](https://github.com/reagent-project/reagent) + [re-frame](https://github.com/Day8/re-frame), a CLJS React wrapper and state management framework, covers the single point of truth (state), dispatch, and query pattern concepts (example code)
- [Om Next](https://github.com/omcljs/om/wiki/Quick-Start-%28om.next%29), a CLJS React framework, covers using queries and graphs, along with a look at property based testing. (example code)

**Comment by w1zeman1p** [comment]
Fantastic! Super stoked to hear about these things. How about May 10?

**Comment by Seberius** [comment]
That works.

**Comment by w1zeman1p** [comment]
Thanks, @Seberius for this great talk at Reno.js 👍
