### ISSUE TITLE
A Call For Help

### ISSUE THREAD

**Issue by elskwid** [renodevelopers/meetups#68]
It's a new year and I believe it's time for us to look at what `/dev/reno` is all about. I have some big ideas for what we can do this year but I need help!

Here's just a few of my ideas:
* Schedule talks months in advance (I know, weird right?!?!)
* Bring in people from out of town to share their stories with us
* Have a regularly scheduled code dojo event
* Do more with our monthly lunches
* Get a book club going (maybe for the lunch-time meetings?)
* Figure out what we want out of the meetups
* Grow our family of developers by reaching out to other communities/organizations
* Actually have the correct number of hosts for the Reno Collective meetings
* Rotate who hosts the meetings
* Start recording our monthly meetings
* A web presence outside of the meetup site/github org

As you can see, that's too much for a single person. So ... I need you to help me. 

Please join me at the January [meeting (Jan 25 @ 6PM)](http://www.meetup.com/dev-reno/events/228260858/) to help me organize. The only way for us to get better is to do it together.

**Comment by underparnv** [comment]
:+1: Will be there and will lend a hand as I'm able.

**Comment by w1zeman1p** [comment]
Some notes from the meeting:
/dev/reno - help me meeting notes

## More People
+ can we do more w/more?
+ stable attendance
+ expose something new
## Lunches
##Interest Groups 
## Website 
+ maybe Christopher
+ talk suggestions with voting
## Books / Papers
+ Jeremy started up the `#books` channel in slack, check it out!
## Host
## Talks
+ Full stack / keep it diverse
+ Generic / General
+ Patterns
    + no walkthrough
## Code Dojo (March?)
+ going through scrum or a condenced SDE workflow in a weekend
+ node school
+ include specific patterns in code dojos
## Relationship to R/C code academy
## Networking
## Ask an Expert (June)
+ 4 experts at 4 different tables
##Streaming / Recorded

**Comment by w1zeman1p** [comment]
Thanks @elskwid for running this one! Opened a lot of eyes to the possibilities and areas that need help.
