### ISSUE TITLE
Pattern meeting - Decorator, Adapter, Singleton

### ISSUE THREAD

**Issue by w1zeman1p** [renodevelopers/meetups#69]
The first pattern meeting is in February. We'll discuss Decorator, Adapter and Singleton

Try to implement these patterns in your language of choice. make a pr to this repo with your code in the design-pattern/{pattern} directories and lets see if we can get some solid examples for reference

**Comment by w1zeman1p** [comment]
Take a look at the adapter pattern for examples! Thanks, @staxmanade.

**Comment by w1zeman1p** [comment]
Suggestions for the format? Someone said no walkthroughs in the help meeting.

**Comment by Chalekian** [comment]
I could give a brief talk on the Hillside Group Patterns Community.  

Started in the 90's, the very best minds for creating/discussing patterns originate here.  Check out their member list and you'll find the most foundation voices--including Helm, Johnson (think "Gang of Four"), Booch, Fowler and more.
  
You can also browse Hillside's in-depth patterns catalogs.  

In short, there is a proven way to talk about patterns...
   ...could be helpful.

Paul Chalekian

**Comment by w1zeman1p** [comment]
Might be nice to have a history of design patterns. Still working out the format for this. Any volunteers to talk about:

* [ ] Adapter
* [ ] Singleton
* [ ] Decorator

@staxmanade looks like you added all the adapter stuff.

The _lightning_ talks will be 25-30 min. Each will answer at least these questions about each pattern. 

+ What problem is this pattern good at solving?
+ What are some code smells that will help me remember to use this pattern?
+ What languages does this pattern work well / not so well in?
+ Are there any well known frameworks that make heavy use of this pattern?

**Comment by w1zeman1p** [comment]
@all, bump. Thinking the format could be: we split off and pair through implementing these in different languages and then come back together to discuss for the last 30-45 min.

**Comment by Chalekian** [comment]
K...   ...there are ways to talk about Design Patterns.  I can review them quickly, prior to our groups splitting off.  I can then rotate between groups.  Remember, this is a creative process with a proven structure.

In short, a pattern has a:

     Context
     Problem
     Forces
     Solution
     Consequences

Consider the following written/illustrated by a "patterns guy" in Germany.

http://www.hillside.net/plop/2010/papers/kohls.pdf

Yes, it is indeed abstract, but remember how Abstraction is part of OOP.  We (in the "Patterns Community") encourage images...   ...and this paper has 'em.

Some of the best minds in software engineering are long "on board" with this.  'could greatly help you all as developers.

I'm open to intermediate questions/consultations.

Best,

Paulie

Paul Chalekian, PhD, CISA

(775) 220-3174 cl.


________________________________

**Comment by w1zeman1p** [comment]
@Chalekian  sounds good! :) you're on

**Comment by w1zeman1p** [comment]
@Chalekian could you shoot me a bio for the event? cjavilla@gmail.com

**Comment by w1zeman1p** [comment]
Awesome job, @Chalekian :)
