### ISSUE TITLE
Message Queues (RabbitMQ, ActiveMQ, ZeroMQ)

### ISSUE THREAD

**Issue by w1zeman1p** [renodevelopers/meetups#75]
What is a Message Queue? Why would I use one? Show me some code examples of using a message queue in real life.

Any volunteers?

**Comment by JeremyBuchmann** [comment]
I'm planning on using RabbitMQ on an upcoming project, so I should be able to do an "Intro to Message Queues" at some point in the future.

**Comment by w1zeman1p** [comment]
Awesome! This one is slated for November. Think you could have something ready for then? (I'll ping you as the date nears)

**Comment by scaryuncledevin** [comment]
If you need a backup or a second I have been working with Amazon SQS recently and can have something ready for November (plenty of time between now and then)

**Comment by w1zeman1p** [comment]
Perfect! It would be cool to have a few different options in the mix

**Comment by w1zeman1p** [comment]
Lets have @JeremyBuchmann do an Intro to Queues and RabbitMQ talk (40 min)
and then @scaryuncledevin do a follow up "here's how I use Amazon SQS" (40 min)

**Comment by JeremyBuchmann** [comment]
I think November would be plenty of time for me, but having a backup or co-presenter would be awesome.

**Comment by w1zeman1p** [comment]
:+1:

**Comment by jimbrowne** [comment]
If you need a backup backup I can talk about Amazon SQS (and SNS) if available that month.

**Comment by TopperKain** [comment]
I'd be happy to talk to Azure Queues, Topics, and Event Hubs as well.

**Comment by scaryuncledevin** [comment]
I know we still have a few months until then but I'm no longer working with SQS. I can still give a quick overview on it if you like though.

**Comment by JeremyBuchmann** [comment]
I'm currently using RabbitMQ, though not in a very "advanced" way (there are a lot of features). I'm not sure I could fill 40 minutes...maybe 20-30.

**Comment by Seberius** [comment]
Hey, @JeremyBuchmann and @scaryuncledevin, how would you like to do a RabbitMQ and SQS talk on the same night at the dev/reno meetup?  Would both of you be good for Sep 26 or Oct 24?

**Comment by JeremyBuchmann** [comment]
@Seberius we have this one scheduled for November already...are you suggesting moving it up? I wouldn't be able to do September, but October would be possible if we need to move things around.

**Comment by Seberius** [comment]
Oops, I missed that, lets leave it where it is.

**Comment by JeremyBuchmann** [comment]
Ok, cool

**Comment by Seberius** [comment]
@scaryuncledevin I know you are doing the Gulp.js presentation at the RenoJS meetup the same month, are you still available to do a quick overview (20 - 30 minutes) of Amazon SQS?

**Comment by scaryuncledevin** [comment]
I could give maybe a 10 to 20 minute overview of SQS. I was under the impression there were supposed to be a few people showing a few different queue systems, and I'm not even using it anymore so I'm a little rusty, and I'm still working on my gulp presentation.

**Comment by JeremyBuchmann** [comment]
@scaryuncledevin and @Seberius I can give the first presentation which can include points such as "What is a queuing system", "Why would you need one", "What are some use cases" before I even get into the specifics of RabbitMQ. Then, @scaryuncledevin can go after me and cover the specifics of SQS so his can be fairly short.

**Comment by Seberius** [comment]
Yea, a quick 10 minute overview focusing on what area SQS excels at/why you chose it would be great.  I think just being able to answer peoples questions on your experience with it would fill out the rest of the time, seeing as there always seems to be quite a bit of interest in AWS.

**Comment by scaryuncledevin** [comment]
This sounds like a good plan, I'll work on it.

**Comment by Seberius** [comment]
Thanks to both of you for the awesome presentation!
