### ISSUE TITLE
Code Kata

### ISSUE THREAD

**Issue by w1zeman1p** [renodevelopers/meetups#81]
Lets do a code kata.

We can organically pair, organized pair, solo, three amigos style however folks want to do it. I'm happy to develop some exercises and constraints. 

Also, opening up for suggestions for exercises here. (Think of problems that can be solved in about 15-30 min by average developer in their language of choice)

**Comment by Seberius** [comment]
For an idea, build a simple Least Recently Used (LRU) cache.  Should take a max size at creation and provide `get`, `set`, and `evict` as methods.  Would touch on some concepts around extending classes, linked lists, and hashmaps.  Should take 20 - 30 minutes.  I have example code in JS and Ruby for reference.

**Comment by w1zeman1p** [comment]
Done and done!
