### ISSUE TITLE
GraphQL/Relay

### ISSUE THREAD

**Issue by Seberius** [renodevelopers/meetups#82]
I can do an introductory talk to GraphQL/Relay.  I was thinking of integrating with Redis for the demo, but if anyone is interested in a specific database, let me know.

**Comment by w1zeman1p** [comment]
@Seberius Think you'd be ready to do this in August?

**Comment by Seberius** [comment]
Sure. RenoJS?

**Comment by w1zeman1p** [comment]
Yeah that's what I was thinking for this one. We could do the general graph db one for /dev/reno if you wanted? Which of the two do you prefer? Also, @Seberius it looks like /dev/reno July is opening up :)
