### ISSUE TITLE
Neo4J/Graph Databases

### ISSUE THREAD

**Issue by Seberius** [renodevelopers/meetups#83]
I am willing to do an introductory talk to Neo4J, a graph database.  The talk would cover the demo provided with database, an overview of some of the published use case studies, and a simple demo app.

**Comment by w1zeman1p** [comment]
@Seberius same question, think you'd be ready for this one in August? Which of these two topics (neo4j and graphql/relay) interest you more?

**Comment by Seberius** [comment]
I could do this in August as well.  I am trying to use both together for a project, so I can develop the presentations alongside one another, and Neo4J has a great visual/live coding tutorial I will probably use.

**Comment by Seberius** [comment]
I just saw your message on July, I can commit to that.  Like I said, the Neo4J tutorial is great, so I can wing worst case scenario (I should have more ready though).

**Comment by w1zeman1p** [comment]
@Seberius will do this talk July 25 :)
