### ISSUE TITLE
Gulp.js

### ISSUE THREAD

**Issue by Seberius** [renodevelopers/meetups#86]
Gulp is a task/build runner for development.

**Comment by scaryuncledevin** [comment]
So I said I would do this one, when would you like me to try to present?

**Comment by Seberius** [comment]
@scaryuncledevin The dates currently open are Oct 11, Nov 8, Dec 13 and Jan 10.  I currently have a backup talk scheduled for Oct 11, so don't feel you need to take that one.  I would prefer to fill up the earlier meetings first, so let me know which you are available for.

**Comment by scaryuncledevin** [comment]
Sounds good, let's plan for Nov 8, I've been working on my presentation but it's not complete.

**Comment by Seberius** [comment]
Perfect

**Comment by Seberius** [comment]
Thank you for the great talk! Code examples from the talk: https://github.com/scaryuncledevin/gulp-example
