### ISSUE TITLE
Building HTTP APIs

### ISSUE THREAD

**Issue by hekaldama** [renodevelopers/meetups#92]
## Overview

Learn the basics about what is a HTTP API, an example when to use it, and build one together to talk to another API.
## Prerequisites

Knowledge of programming in any language. A computer / access to host with docker installed or a working `ruby` env. If you don't have these things, you will be able to pair up with others that do and learn alongside them.
## Learning Outcomes
- Learn about grape web framework
- Learn how to write a HTTP API
## Resources

Grape - https://github.com/intridea/grape
Demo Repo - https://github.com/hekaldama/building-http-apis
Slide Show - https://docs.google.com/a/avil.la/presentation/d/1FvzgpR-a4IqZV-8VnPkW7zHeM3gUFcddFRr4YeafuXw/edit?usp=sharing

**Comment by Seberius** [comment]
Hey Adam, thanks for taking this up on short notice.  Let me know if you need anything for Monday. Thanks!

**Comment by hekaldama** [comment]
Sure thing. Some questions:
- How long do I have?
- Do people bring computers?
- Is it reasonable to have "Prerequisites"?
- Would you like to tag team where I do 30-40min / break for 10min / you do 30-40min talk?

**Comment by Seberius** [comment]
- You usually have as much time as you want, the presentations usually runs 45 - 90 minutes.  People will usually have quite a few questions.
- Most have a computer.  We have a done a pair programming meetup before and it was well received.  I will get some details up on the Meetup page once I have access so people know what to expect.
- We have had meetings in the past with prerequisites.  We can always work through them if there is an issue.
- We usually try to keep it to one topic, as the first always seems to run longer than expected.

**Comment by hekaldama** [comment]
Thank you all for coming and if you want to see my pass at programming the craigslist API, I pushed it to:

https://github.com/hekaldama/building-http-apis/blob/my_cl/config.ru

Feel free to post your takes here in a gist / repo / inline and we can chat about them.
